spring:
  profiles.active: development

---

spring:
  profiles: STG
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: centric
    password:
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: products.centric.com
    test-connection: false
flyway:
  enabled: false
server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/xml,application/json


---

spring:
  main:
    allow-bean-definition-overriding: true
  profiles: development
  datasource:
    url: jdbc:h2:mem:products_QA;DB_CLOSE_DELAY=-1;LOCK_TIMEOUT=5000
    driver-class-name: org.h2.Driver
    username: centric
    password:  
  jpa:
      show-sql: false
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
flyway:
  enabled: true
products:
  host: localhost



---

spring:
  profiles: PRODUCTION
  datasource:
    invoices:
      url: jdbc:postgresql://localhost:5432/products
      username: centric
      password:
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: products.centric.com
    test-connection: false
flyway:
  enabled: false
server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/xml,application/json

---

spring:
  profiles: PREPROD
  datasource:
    invoices:
      url: jdbc:postgresql://localhost:5432/products
      username: centric
      password:
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: products.centric.com
    test-connection: false
flyway:
  enabled: false
server:
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/xml,application/json


